config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#fb_test1'

  match '/pipeline', to: 'pages#pipeline', via: 'get'

  match '/help', to: 'pages#help', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'

  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :users do
    member do
      get :attending
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :eu_rels, only: [:create, :destroy]

  resources :events  do
    member do
      get :attenders
    end
  end
  

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-error">
		The form contains <%= pluralize(object.errors.count, "error") %>
		</div>
		<ul>
			<%= object.errors.full_messages.each do |msg| %>
			<li>* <%= msg %></li>
			<% end %>
		</ul> 
		</div>
<% end %>

app/views/shared/_event_form.html.erb
<div class="container">

<%= form_for(@event) do |f| %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :comment %>
      <%= f.text_area :comment %>

      <%= f.label :points %>
      <%= f.number_field :points %>

     

      <%= f.submit "Create Event", class: "btn btn-large btn-primary" %>
    <% end %>
</div>

<!-- Datetime, organization, etc.(not urgent) still to be added in this form when creating an event -->

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="events">
    <%= render partial: 'shared/feed_item', collection: @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_feed_item.html.erb
<li id="<%= feed_item.id %>">
  <%= link_to gravatar_for(feed_item.user), feed_item.user %>
    <span class="user">
      <%= link_to feed_item.user.name, feed_item.user %>
    </span>
    <span class="comment"><%= feed_item.comment %></span>
    <span class="timestamp">
      Posted <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  <% if current_user?(feed_item.user) %>
    <%= link_to "delete", feed_item, method: :delete,
                                     data: { confirm: "You sure?" },
                                     title: feed_item.comment %>
  <% end %>
</li>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= attending_user_path(@user) %>">
  <strong id="following" class="stat">
      <!-- show check in events here -->
      # attended events 
    </strong>
  </a>
</div>

app/views/shared/_statse.html.erb
 <a href="<%= attenders_event_path(@event) %>">
    <strong id="attenders" class="stat">
      <%= @event.attenders.count %>
    </strong>
    people attending this event.
  </a>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 52), current_user %>
<h1>
  <%= current_user.name %>
</h1>
<span>
  <%= link_to "view my profile", current_user %>
</span>
<span>
  <%= pluralize(current_user.events.count, "event") %>
</span>