config/routes.rb
Rails.application.routes.draw do
  
  root 'pages#fb_test1'

  match '/pipeline', to: 'pages#pipeline', via: 'get'

  match '/help', to: 'pages#help', via: 'get'

  match '/signup', to: 'users#new', via: 'get'

  match '/signin', to: 'sessions#new', via: 'get'

  match '/signout', to: 'sessions#destroy', via: 'delete'

  resources :users do
    member do
      get :attending
    end
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :eu_rels, only: [:create, :destroy]

  resources :events  do
    member do
      get :attenders
    end
  end
  

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation" id="black-attempt">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <!-- Logo and Help -->

      <a class="navbar-brand" href="/pipeline" id="logo">Pipeline</a>
    </div>
    
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="nav_text"><a href="#" class="nav_text">Help</a></li>
       
        <!-- Organizations Dropdown -->
       
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Organizations <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "HSA", users_path %></li>
            
          </ul>
        </li>
      </ul>

      <!-- Right side of nav w/ different displays for loged in vs. non-logged in users -->

      <ul class="nav navbar-nav navbar-right">
         
        <% if signed_in? %>
            
          <li><%= link_to "Events", events_path %></li>
          <li class="dropdown">
            <!-- Signed in dropdown -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Sign Out", signout_path, method: "delete" %></li>
            </ul>
        
          <% else %>
            <li><%= link_to "Sign Up", signup_path %></li>       
            <li><%= link_to "Login", signin_path %></li>
          <% end %>
      
      </ul>

    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CalD1</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
</head>
<body>

<%= render 'layouts/header' %>
<% flash.each do |key, value| %>
	<div class="alert alert-<%= key %>"><%= value %></div>
<% end %>
<%= yield %>

</body>
</html>